### ISSUE TITLE
Expanding the definition with additional categories?

### ISSUE THREAD

**Issue by coni2k** [FOSSRIT/open-work-definition#7]
Would you consider expanding the definition with additional categories? For example:
- Literature
- Journalism
- Sounds, music
- Videos, movies

It looks like Creative Commons can be used for all these categories, but curious about what you think:
https://wiki.creativecommons.org/wiki/Case_Studies

**Comment by Nolski** [comment]
While CC is a licensing regime and not really a definition, there are some differences between our two project. However, all of the above are considered "Work" to us and therefore should be included! Definitely more sections describing these things would be accepted via PR.

**Comment by coni2k** [comment]
Great, thanks for the answer. I'd love to prepare a PR, but I can't do it promptly. So, I will close the issue.
